select C.NOMECLIENTE,
       PED.PEDIDOID AS NR_PEDIDO,
       COUNT(PED.PRODUTOID) AS QT_ITEM,
       LISTAGG(PRO.NOMEPRODUTO,', ') AS ITEM
         from PEDIDO PED
         
 INNER JOIN CLIENTES C
ON C.CLIENTEID = PED.CLIENTEID

INNER JOIN PRODUTOS PRO
ON PRO.PRODUTOID = PED.PRODUTOID

GROUP BY C.NOMECLIENTE,
         PED.PEDIDOID;